/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWorkersRouteImport } from './routes/admin/workers'
import { Route as AdminWastageRulesRouteImport } from './routes/admin/wastage-rules'
import { Route as AdminVeneersRouteImport } from './routes/admin/veneers'
import { Route as AdminTrackRouteImport } from './routes/admin/track'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminSeedRouteImport } from './routes/admin/seed'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminRemakesRouteImport } from './routes/admin/remakes'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPricingRulesRouteImport } from './routes/admin/pricing-rules'
import { Route as AdminPricingFactorsRouteImport } from './routes/admin/pricing-factors'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMaterialsRouteImport } from './routes/admin/materials'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminFinishesRouteImport } from './routes/admin/finishes'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCostAnalysisRouteImport } from './routes/admin/cost-analysis'
import { Route as AdminAccessoriesRouteImport } from './routes/admin/accessories'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin/quotes/index'
import { Route as AdminQuotesNewRouteImport } from './routes/admin/quotes/new'
import { Route as AdminQuotesConfiguratorRouteImport } from './routes/admin/quotes/configurator'
import { Route as AdminQuotesIdRouteImport } from './routes/admin/quotes/$id'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin/invoices.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWastageRulesRoute = AdminWastageRulesRouteImport.update({
  id: '/wastage-rules',
  path: '/wastage-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeneersRoute = AdminVeneersRouteImport.update({
  id: '/veneers',
  path: '/veneers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackRoute = AdminTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemakesRoute = AdminRemakesRouteImport.update({
  id: '/remakes',
  path: '/remakes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRulesRoute = AdminPricingRulesRouteImport.update({
  id: '/pricing-rules',
  path: '/pricing-rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingFactorsRoute = AdminPricingFactorsRouteImport.update({
  id: '/pricing-factors',
  path: '/pricing-factors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinishesRoute = AdminFinishesRouteImport.update({
  id: '/finishes',
  path: '/finishes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostAnalysisRoute = AdminCostAnalysisRouteImport.update({
  id: '/cost-analysis',
  path: '/cost-analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessoriesRoute = AdminAccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesNewRoute = AdminQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesConfiguratorRoute = AdminQuotesConfiguratorRouteImport.update({
  id: '/quotes/configurator',
  path: '/quotes/configurator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesIdRoute = AdminQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/track': typeof TrackRoute
  '/admin/accessories': typeof AdminAccessoriesRoute
  '/admin/cost-analysis': typeof AdminCostAnalysisRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/finishes': typeof AdminFinishesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing-factors': typeof AdminPricingFactorsRoute
  '/admin/pricing-rules': typeof AdminPricingRulesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/remakes': typeof AdminRemakesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/track': typeof AdminTrackRoute
  '/admin/veneers': typeof AdminVeneersRoute
  '/admin/wastage-rules': typeof AdminWastageRulesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/quotes/configurator': typeof AdminQuotesConfiguratorRoute
  '/admin/quotes/new': typeof AdminQuotesNewRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/track': typeof TrackRoute
  '/admin/accessories': typeof AdminAccessoriesRoute
  '/admin/cost-analysis': typeof AdminCostAnalysisRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/finishes': typeof AdminFinishesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing-factors': typeof AdminPricingFactorsRoute
  '/admin/pricing-rules': typeof AdminPricingRulesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/remakes': typeof AdminRemakesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/track': typeof AdminTrackRoute
  '/admin/veneers': typeof AdminVeneersRoute
  '/admin/wastage-rules': typeof AdminWastageRulesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/quotes/configurator': typeof AdminQuotesConfiguratorRoute
  '/admin/quotes/new': typeof AdminQuotesNewRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/track': typeof TrackRoute
  '/admin/accessories': typeof AdminAccessoriesRoute
  '/admin/cost-analysis': typeof AdminCostAnalysisRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/finishes': typeof AdminFinishesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing-factors': typeof AdminPricingFactorsRoute
  '/admin/pricing-rules': typeof AdminPricingRulesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/remakes': typeof AdminRemakesRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/seed': typeof AdminSeedRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/track': typeof AdminTrackRoute
  '/admin/veneers': typeof AdminVeneersRoute
  '/admin/wastage-rules': typeof AdminWastageRulesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/quotes/$id': typeof AdminQuotesIdRoute
  '/admin/quotes/configurator': typeof AdminQuotesConfiguratorRoute
  '/admin/quotes/new': typeof AdminQuotesNewRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/track'
    | '/admin/accessories'
    | '/admin/cost-analysis'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/finishes'
    | '/admin/health'
    | '/admin/invoices'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing-factors'
    | '/admin/pricing-rules'
    | '/admin/products'
    | '/admin/remakes'
    | '/admin/requests'
    | '/admin/seed'
    | '/admin/suppliers'
    | '/admin/track'
    | '/admin/veneers'
    | '/admin/wastage-rules'
    | '/admin/workers'
    | '/admin/'
    | '/admin/invoices/$id'
    | '/admin/quotes/$id'
    | '/admin/quotes/configurator'
    | '/admin/quotes/new'
    | '/admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/track'
    | '/admin/accessories'
    | '/admin/cost-analysis'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/finishes'
    | '/admin/health'
    | '/admin/invoices'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing-factors'
    | '/admin/pricing-rules'
    | '/admin/products'
    | '/admin/remakes'
    | '/admin/requests'
    | '/admin/seed'
    | '/admin/suppliers'
    | '/admin/track'
    | '/admin/veneers'
    | '/admin/wastage-rules'
    | '/admin/workers'
    | '/admin'
    | '/admin/invoices/$id'
    | '/admin/quotes/$id'
    | '/admin/quotes/configurator'
    | '/admin/quotes/new'
    | '/admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/track'
    | '/admin/accessories'
    | '/admin/cost-analysis'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/finishes'
    | '/admin/health'
    | '/admin/invoices'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/pricing-factors'
    | '/admin/pricing-rules'
    | '/admin/products'
    | '/admin/remakes'
    | '/admin/requests'
    | '/admin/seed'
    | '/admin/suppliers'
    | '/admin/track'
    | '/admin/veneers'
    | '/admin/wastage-rules'
    | '/admin/workers'
    | '/admin/'
    | '/admin/invoices/$id'
    | '/admin/quotes/$id'
    | '/admin/quotes/configurator'
    | '/admin/quotes/new'
    | '/admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wastage-rules': {
      id: '/admin/wastage-rules'
      path: '/wastage-rules'
      fullPath: '/admin/wastage-rules'
      preLoaderRoute: typeof AdminWastageRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veneers': {
      id: '/admin/veneers'
      path: '/veneers'
      fullPath: '/admin/veneers'
      preLoaderRoute: typeof AdminVeneersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/track': {
      id: '/admin/track'
      path: '/track'
      fullPath: '/admin/track'
      preLoaderRoute: typeof AdminTrackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/remakes': {
      id: '/admin/remakes'
      path: '/remakes'
      fullPath: '/admin/remakes'
      preLoaderRoute: typeof AdminRemakesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-rules': {
      id: '/admin/pricing-rules'
      path: '/pricing-rules'
      fullPath: '/admin/pricing-rules'
      preLoaderRoute: typeof AdminPricingRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-factors': {
      id: '/admin/pricing-factors'
      path: '/pricing-factors'
      fullPath: '/admin/pricing-factors'
      preLoaderRoute: typeof AdminPricingFactorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finishes': {
      id: '/admin/finishes'
      path: '/finishes'
      fullPath: '/admin/finishes'
      preLoaderRoute: typeof AdminFinishesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cost-analysis': {
      id: '/admin/cost-analysis'
      path: '/cost-analysis'
      fullPath: '/admin/cost-analysis'
      preLoaderRoute: typeof AdminCostAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accessories': {
      id: '/admin/accessories'
      path: '/accessories'
      fullPath: '/admin/accessories'
      preLoaderRoute: typeof AdminAccessoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/new': {
      id: '/admin/quotes/new'
      path: '/quotes/new'
      fullPath: '/admin/quotes/new'
      preLoaderRoute: typeof AdminQuotesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/configurator': {
      id: '/admin/quotes/configurator'
      path: '/quotes/configurator'
      fullPath: '/admin/quotes/configurator'
      preLoaderRoute: typeof AdminQuotesConfiguratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/$id': {
      id: '/admin/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AdminQuotesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
  }
}

interface AdminInvoicesRouteChildren {
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
}

const AdminInvoicesRouteChildren: AdminInvoicesRouteChildren = {
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
}

const AdminInvoicesRouteWithChildren = AdminInvoicesRoute._addFileChildren(
  AdminInvoicesRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessoriesRoute: typeof AdminAccessoriesRoute
  AdminCostAnalysisRoute: typeof AdminCostAnalysisRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminFinishesRoute: typeof AdminFinishesRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminInvoicesRoute: typeof AdminInvoicesRouteWithChildren
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingFactorsRoute: typeof AdminPricingFactorsRoute
  AdminPricingRulesRoute: typeof AdminPricingRulesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRemakesRoute: typeof AdminRemakesRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSeedRoute: typeof AdminSeedRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTrackRoute: typeof AdminTrackRoute
  AdminVeneersRoute: typeof AdminVeneersRoute
  AdminWastageRulesRoute: typeof AdminWastageRulesRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuotesIdRoute: typeof AdminQuotesIdRoute
  AdminQuotesConfiguratorRoute: typeof AdminQuotesConfiguratorRoute
  AdminQuotesNewRoute: typeof AdminQuotesNewRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessoriesRoute: AdminAccessoriesRoute,
  AdminCostAnalysisRoute: AdminCostAnalysisRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminFinishesRoute: AdminFinishesRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminInvoicesRoute: AdminInvoicesRouteWithChildren,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingFactorsRoute: AdminPricingFactorsRoute,
  AdminPricingRulesRoute: AdminPricingRulesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRemakesRoute: AdminRemakesRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSeedRoute: AdminSeedRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTrackRoute: AdminTrackRoute,
  AdminVeneersRoute: AdminVeneersRoute,
  AdminWastageRulesRoute: AdminWastageRulesRoute,
  AdminWorkersRoute: AdminWorkersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminQuotesIdRoute: AdminQuotesIdRoute,
  AdminQuotesConfiguratorRoute: AdminQuotesConfiguratorRoute,
  AdminQuotesNewRoute: AdminQuotesNewRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
